commands.py

Adds IBIP compatibility to cybot.
[IBIP](https://github.com/Teknikode/IBIP) is a protocol for detecting and enumerating robots on an IRC network. It's currently in a drafting stage, but we don't expect the actual format of the response to change.

add IBIP compatibility

---

commands.py

fix shitposts parsing

---

commands.py
texts/other/linus.txt
texts/other/stallman.txt

added linus command

---

commands.py

fixed eightball 

---

commands.py
fourchan_json.py

ppl in the channel were doing this as a joke, I made it real
I don't know python tho so it's not very DRY
pls respond

.shitpost from /board/

---

commands.py
fourchan_json.py

Reverting until this is a truly random function which actually works

Revert ".shitpost from /board/"

---

commands.py

added posture reminder

---

commands.py
reddit.py
requirements.txt

Replaced praw with custom implementation, now the comments are selected from hot posts which maximizes a chance of finding a comment. There is a non-zero chance that this PR works.

Rewritten le to improve error handling

---

commands.py
fourchan_json.py

There is a chance that possibly this code could work under certain conditions.

Command shitpost correctly applies colors to the output

---

commands.py

Lets not do what Facebook engineers love doing as can be seen in the leaked code.

Removed multiple imports

---

commands.py
fourchan_pic.py

Added lich_bots 4chan pic function

---

.gitignore
README.md
config.json
irc.py

Another feature from lich_bot goes into cybits.

Added json configuration

---

commands.py

tested local copy, transcribed manually on github so gl;hf :DDD

fugged x-DD

---

commands.py
requirements.txt

Remember to include what the bots needs.

Added what the bot needs to run fine.

---

irc.py

fix /QUOTE PONG thing for real

---

commands.py

:disappointed: never more git squashing :disappointed:

Added reddit picture,wiki function and ZWS

---

texts/other/guinea.txt

Removed a dead link

---

commands.py

Didnt test

---

.gitignore
commands.py
reddit.py

Eww global variables tho. Also add temp files to gitignore.

Add .lelast - get URL of last random reddit

---

reddit.py

Reddit punishes people doing things with their user agents

---

commands.py

For whatever fucking reason, it was parsing it wrong.

Unfuck untappd unicode

---

commands.py
reddit.py

Also, I switched [this](https://github.com/cybits/cybot/compare/master...ableiten:master#diff-4d74b15d9b9e10adb408c5a530f62c93R46) to just use the first entry because I think they're already sorted randomly by Reddit. Let me know if they aren't and I'll switch it back.

.lelong for great mgtow memes

---

commands.py
irc.py

Add Twitter posting

---

commands.py

we https now

---

commands.py

Reinventing the wheel 1 meme at a time

More string stuff

---

commands.py

- .sq for stripping 4chan quotes
- .center for memeing on people who care about life

2 New Commands

---

commands.py

Add .tw alias for .tweet

---

commands.py
pornhub.py

This bastard took longer than I'm willing to admit. I should listen more

.porntitle... cause porno titles are fantastic works of art

---

CODE_OF_CONDUCT.md
README.md

added necessary user reviews

---

config.json.example

added better generics to JSON example

---

cacher.py

check it out, there shouldn't be any empty files here!

made sure cacher.py isn't empty

---

README.md

dunno but that was really bothering me for a long time

fixed arrows in code block to clearer comment #'s
